---
name: xcop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: g4s8/xcop-action@master
